import '@/global.css';

import { Platform } from 'react-native';

const BRAND = {
  sand: '#F2D094',
  sandSoft: '#FBF3E3',
  sandGlow: '#F7E0B5',
  sandDeep: '#D7B170',
  beige: '#F7EBDC',
  beigeSoft: '#FFF9F1',
  beigeAlt: '#F4E2CB',
  red: '#F42245',
  redPressed: '#D41738',
  redSoft: '#FFE1E6',
  ink: '#141210',
  inkSoft: '#2B241F',
  inkMuted: '#5F5349',
  inkSubtle: '#8D7E71',
  border: '#E6D2B8',
  borderSoft: '#F0E2CF',
  heroDark: '#1D1714',
  heroWarm: '#3A2A23',
  sceneBg: '#181311',
  sceneSurface: '#241C18',
  sceneSurfaceAlt: '#302621',
  sceneBorder: '#4B3B31',
  sceneText: '#FFF5E7',
  sceneMuted: '#D9C6AF',
  sceneSubtle: '#B9A38C',
  success: '#247E57',
  successSoft: '#E3F4EA',
  warning: '#B9791A',
  warningSoft: '#FFF2DB',
  danger: '#C34A4B',
  dangerSoft: '#FBE5E6',
  info: '#85513D',
  infoSoft: '#F5E7DE',
  white: '#FFFFFF',
  shadow: 'rgba(20,18,16,0.12)',
  shadowStrong: 'rgba(20,18,16,0.18)',
} as const;

export const BrandPalette = {
  ...BRAND,
  background: BRAND.beige,
  backgroundAlt: '#F9F0E4',
  surface: BRAND.beigeSoft,
  surfaceAlt: BRAND.beigeAlt,
  surfaceMuted: '#F5E6D3',
  text: BRAND.ink,
  textMuted: BRAND.inkMuted,
  textSubtle: BRAND.inkSubtle,
  muted: BRAND.inkMuted,
  subtle: BRAND.inkSubtle,
  border: BRAND.border,
  line: BRAND.borderSoft,
  primary: BRAND.red,
  primarySoft: BRAND.redSoft,
  primaryPressed: BRAND.redPressed,
  accent: BRAND.sand,
  accentSoft: BRAND.sandGlow,
  success: BRAND.success,
  successSoft: BRAND.successSoft,
  warning: BRAND.warning,
  warningSoft: BRAND.warningSoft,
  danger: BRAND.danger,
  dangerSoft: BRAND.dangerSoft,
  info: BRAND.info,
  infoSoft: BRAND.infoSoft,
  shadow: BRAND.shadow,
  shadowStrong: BRAND.shadowStrong,
  chip: '#FFF7ED',
  chipAlt: '#F9E9D5',
  hero: BRAND.heroDark,
  tabBar: 'rgba(255,248,240,0.98)',
  page: BRAND.beige,
  card: BRAND.beigeSoft,
  white: BRAND.white,
  black: BRAND.ink,
  ink: BRAND.ink,
  inkSoft: BRAND.inkSoft,
  cream: BRAND.beige,
  creamSoft: BRAND.beigeSoft,
  creamAlt: BRAND.beigeAlt,
  peach50: BRAND.redSoft,
  peach100: '#F9E2C1',
  peach200: BRAND.sand,
  peach300: '#EABD75',
  peach400: '#DAA35C',
  peach500: '#C6854B',
  peach600: BRAND.red,
  brown: BRAND.inkSoft,
  brownDark: BRAND.ink,
  orange: BRAND.red,
  orangeSoft: BRAND.redSoft,
  blue: BRAND.info,
  blueSoft: BRAND.infoSoft,
  green: BRAND.success,
  pill: '#FFF7ED',
  pillDark: BRAND.sceneSurfaceAlt,
  sceneBg: BRAND.sceneBg,
  sceneSurface: BRAND.sceneSurface,
  sceneSurfaceAlt: BRAND.sceneSurfaceAlt,
  sceneBorder: BRAND.sceneBorder,
  sceneText: BRAND.sceneText,
  sceneMuted: BRAND.sceneMuted,
  darkPage: BRAND.sceneBg,
  darkSurface: BRAND.sceneSurface,
  darkSurfaceAlt: BRAND.sceneSurfaceAlt,
  darkBorder: BRAND.sceneBorder,
  darkText: BRAND.sceneText,
  darkMuted: BRAND.sceneMuted,
  darkSubtle: BRAND.sceneSubtle,
  borderDark: BRAND.sceneBorder,
  textDark: BRAND.sceneText,
  textMutedDark: BRAND.sceneMuted,
  textSubtleDark: BRAND.sceneSubtle,
} as const;

export const Colors = {
  light: {
    text: BrandPalette.text,
    background: BrandPalette.background,
    backgroundElement: BrandPalette.surface,
    backgroundSelected: BrandPalette.surfaceAlt,
    textSecondary: BrandPalette.textMuted,
    border: BrandPalette.border,
    primary: BrandPalette.primary,
  },
  dark: {
    text: BrandPalette.sceneText,
    background: BrandPalette.sceneBg,
    backgroundElement: BrandPalette.sceneSurface,
    backgroundSelected: BrandPalette.sceneSurfaceAlt,
    textSecondary: BrandPalette.sceneMuted,
    border: BrandPalette.sceneBorder,
    primary: BrandPalette.accent,
  },
} as const;

export type ThemeColor = keyof typeof Colors.light & keyof typeof Colors.dark;

export const Fonts = Platform.select({
  ios: {
    sans: 'system-ui',
    serif: 'ui-serif',
    rounded: 'ui-rounded',
    mono: 'ui-monospace',
  },
  default: {
    sans: 'normal',
    serif: 'serif',
    rounded: 'normal',
    mono: 'monospace',
  },
  web: {
    sans: 'var(--font-display)',
    serif: 'var(--font-serif)',
    rounded: 'var(--font-rounded)',
    mono: 'var(--font-mono)',
  },
});

export const Spacing = {
  half: 2,
  one: 4,
  two: 8,
  three: 16,
  four: 24,
  five: 32,
  six: 64,
} as const;

export const Radius = {
  sm: 12,
  md: 16,
  lg: 20,
  xl: 24,
  pill: 999,
} as const;

export function createShadow(opacity = 0.12, radius = 18, height = 10) {
  return Platform.select({
    ios: {
      shadowColor: BRAND.ink,
      shadowOpacity: opacity,
      shadowRadius: radius,
      shadowOffset: { width: 0, height },
    },
    android: {
      elevation: Math.max(4, Math.round(radius * 0.75)),
    },
    default: {},
  });
}

export const ConsumerServiceThemes = {
  food: {
    page: BrandPalette.background,
    hero: '#1F1714',
    heroSoft: '#4C3329',
    heroAccent: BrandPalette.accent,
    heroText: BrandPalette.sceneText,
    heroSub: '#E2CEB6',
    searchPlaceholder: 'Search biryani, burgers, desserts...',
    bannerEyebrow: 'Warm comfort, elevated discovery',
    bannerTitle: 'Everyday ordering with sharper search, stronger offers and calmer surfaces',
    bannerCopy:
      'Grab Basket keeps the warmth of local commerce while tightening hierarchy across search, merchant cards and trust cues.',
    statusBar: 'light-content' as const,
  },
  warehouse: {
    page: '#FBF4E8',
    hero: '#F1DFC0',
    heroSoft: '#FFF1DA',
    heroAccent: '#E7B86E',
    heroText: BrandPalette.text,
    heroSub: BrandPalette.textMuted,
    searchPlaceholder: 'Search fruits, dairy, snacks, essentials...',
    bannerEyebrow: 'Quick baskets without clutter',
    bannerTitle: 'Fast grocery browsing with warmer shelves and clearer deal moments',
    bannerCopy:
      'The grocery layer stays high-speed, but cards, chips and promotions now feel like the same Grab Basket family.',
    statusBar: 'dark-content' as const,
  },
  eatout: {
    page: '#FAF0E6',
    hero: '#EFD9C4',
    heroSoft: '#F9EADF',
    heroAccent: '#E5A86D',
    heroText: BrandPalette.text,
    heroSub: BrandPalette.textMuted,
    searchPlaceholder: 'Search restaurants, vibes, areas...',
    bannerEyebrow: 'Plans made easier',
    bannerTitle: 'Reserve tables with richer merchant context, calmer spacing and better offers',
    bannerCopy:
      'Dineout gets a more polished browse-to-book flow without borrowing another brand’s palette or layout.',
    statusBar: 'dark-content' as const,
  },
  scenes: {
    page: BrandPalette.sceneBg,
    hero: '#17110F',
    heroSoft: '#2E221D',
    heroAccent: '#80533F',
    heroText: BrandPalette.sceneText,
    heroSub: BrandPalette.sceneMuted,
    searchPlaceholder: 'Search events, creators, experiences...',
    bannerEyebrow: 'Weekend energy',
    bannerTitle: 'Editorial discovery that still feels unmistakably Grab Basket',
    bannerCopy:
      'The dark experience keeps its nightlife mood while using the same spacing, card treatment and brand red restraint.',
    statusBar: 'light-content' as const,
  },
} as const;

export const StoreServiceThemes = {
  food: {
    page: BrandPalette.background,
    hero: '#1B1411',
    heroAlt: '#4B2D24',
    heroAccent: BrandPalette.accent,
    primary: BrandPalette.primary,
    primarySoft: BrandPalette.primarySoft,
    searchBg: BrandPalette.surface,
    textOnHero: BrandPalette.sceneText,
    pillBg: 'rgba(255,255,255,0.12)',
    pillText: BrandPalette.sceneText,
    cartBg: BrandPalette.ink,
  },
  warehouse: {
    page: '#FBF4E8',
    hero: '#EED7B8',
    heroAlt: '#F8E7D0',
    heroAccent: BrandPalette.primary,
    primary: BrandPalette.primary,
    primarySoft: BrandPalette.primarySoft,
    searchBg: BrandPalette.surface,
    textOnHero: BrandPalette.text,
    pillBg: 'rgba(20,18,16,0.07)',
    pillText: BrandPalette.text,
    cartBg: BrandPalette.ink,
  },
  eatout: {
    page: '#FAF0E6',
    hero: '#E9D4C0',
    heroAlt: '#F4E3D6',
    heroAccent: BrandPalette.primary,
    primary: BrandPalette.primary,
    primarySoft: BrandPalette.primarySoft,
    searchBg: BrandPalette.surface,
    textOnHero: BrandPalette.text,
    pillBg: 'rgba(20,18,16,0.07)',
    pillText: BrandPalette.text,
    cartBg: BrandPalette.ink,
  },
  scenes: {
    page: BrandPalette.sceneBg,
    hero: '#120F0D',
    heroAlt: '#2A211D',
    heroAccent: '#8A5A47',
    primary: BrandPalette.accent,
    primarySoft: 'rgba(255,255,255,0.12)',
    searchBg: BrandPalette.sceneSurface,
    textOnHero: BrandPalette.sceneText,
    pillBg: 'rgba(255,255,255,0.10)',
    pillText: BrandPalette.sceneText,
    cartBg: BrandPalette.accent,
  },
} as const;

const sharedConsumerTabTheme = {
  activeTint: BrandPalette.primary,
  inactiveTint: BrandPalette.textSubtle,
  barBackground: 'rgba(255,248,240,0.99)',
  barBorder: BrandPalette.border,
  shadowColor: BrandPalette.shadowStrong,
  focusedSurface: BrandPalette.primarySoft,
  focusedBorder: '#F3C8D0',
  iconSurface: '#FFF4F1',
  badgeBackground: BrandPalette.primary,
  badgeText: BrandPalette.white,
} as const;

export const ConsumerTabThemes = {
  food: {
    ...sharedConsumerTabTheme,
    sceneBackground: BrandPalette.background,
    titleMap: {
      index: 'Home',
      explore: 'Explore',
      reorder: 'Reorder',
      account: 'Profile',
    },
    iconMap: {
      index: 'home-outline',
      explore: 'compass-outline',
      reorder: 'reload-outline',
      account: 'person-outline',
    },
  },
  warehouse: {
    ...sharedConsumerTabTheme,
    sceneBackground: '#FBF4E8',
    focusedSurface: '#FFF0E2',
    focusedBorder: '#F2D6BF',
    iconSurface: '#FFF0E4',
    titleMap: {
      index: 'Mart',
      explore: 'Aisles',
      reorder: 'Reorder',
      account: 'Profile',
    },
    iconMap: {
      index: 'basket-outline',
      explore: 'grid-outline',
      reorder: 'reload-outline',
      account: 'person-outline',
    },
  },
  eatout: {
    ...sharedConsumerTabTheme,
    sceneBackground: '#FAF0E6',
    focusedSurface: '#FFF0E7',
    focusedBorder: '#EFD1C6',
    iconSurface: '#FFF0E8',
    titleMap: {
      index: 'Dineout',
      explore: 'Explore',
      reorder: 'New & Hot',
      account: 'Profile',
    },
    iconMap: {
      index: 'restaurant-outline',
      explore: 'sparkles-outline',
      reorder: 'flame-outline',
      account: 'person-outline',
    },
  },
  scenes: {
    activeTint: BrandPalette.accent,
    inactiveTint: '#B79D88',
    barBackground: 'rgba(24,19,17,0.98)',
    barBorder: BrandPalette.sceneBorder,
    shadowColor: BrandPalette.shadowStrong,
    focusedSurface: BrandPalette.sceneSurfaceAlt,
    focusedBorder: '#695247',
    iconSurface: '#382B24',
    badgeBackground: BrandPalette.accent,
    badgeText: BrandPalette.text,
    sceneBackground: BrandPalette.sceneBg,
    titleMap: {
      index: 'Scenes',
      explore: 'Explore',
      reorder: 'Saved',
      account: 'Profile',
    },
    iconMap: {
      index: 'sparkles-outline',
      explore: 'compass-outline',
      reorder: 'bookmark-outline',
      account: 'person-outline',
    },
  },
} as const;

export const AppShellThemes = {
  delivery: {
    page: BrandPalette.backgroundAlt,
    barBackground: 'rgba(255,248,240,0.99)',
    barBorder: BrandPalette.border,
    activeTint: BrandPalette.primary,
    inactiveTint: BrandPalette.textSubtle,
    focusedSurface: '#FFF0EA',
    focusedBorder: '#F2C7BB',
    iconSurface: '#FFF6F0',
    shadowColor: BrandPalette.shadowStrong,
  },
  partner: {
    page: '#FBF2E7',
    barBackground: 'rgba(255,248,240,0.99)',
    barBorder: BrandPalette.border,
    activeTint: BrandPalette.primary,
    inactiveTint: BrandPalette.textSubtle,
    focusedSurface: '#FFF1E7',
    focusedBorder: '#E9CCBE',
    iconSurface: '#FFF5EE',
    shadowColor: BrandPalette.shadowStrong,
  },
} as const;

export const BottomTabInset = Platform.select({ ios: 50, android: 80 }) ?? 0;
export const MaxContentWidth = 800;
