import '@/global.css';

import { Platform } from 'react-native';

const BRAND = {
  sand: '#F8D191',
  sandSoft: '#FEF3DE',
  sandMuted: '#F3E3C1',
  sandDeep: '#D8B06E',
  red: '#ED2642',
  redSoft: '#FFE7EA',
  redPressed: '#C81F37',
  ink: '#141210',
  inkSoft: '#2A2521',
  cream: '#FBF6EE',
  creamSoft: '#FFFDF9',
  creamAlt: '#FFF1E0',
  border: '#EBCFB0',
  borderSoft: '#F2E1CC',
  textMuted: '#6D645E',
  textSubtle: '#9A8D81',
  success: '#21845B',
  successSoft: '#E8F6EE',
  warning: '#B77818',
  warningSoft: '#FFF4DF',
  danger: '#C74648',
  dangerSoft: '#FDE9EA',
  info: '#8E4430',
  infoSoft: '#F7E9E1',
  darkPage: '#171310',
  darkSurface: '#201915',
  darkSurfaceAlt: '#2B221D',
  darkBorder: '#4A3A31',
  darkText: '#FFF6EC',
  darkMuted: '#D7C5B4',
  darkSubtle: '#B59F8A',
  shadow: 'rgba(20,18,16,0.14)',
  shadowStrong: 'rgba(20,18,16,0.2)',
} as const;

export const BrandPalette = {
  ...BRAND,
  page: BRAND.cream,
  surface: BRAND.creamSoft,
  surfaceAlt: BRAND.creamAlt,
  surfaceMuted: '#F8EAD6',
  text: BRAND.ink,
  muted: BRAND.textMuted,
  subtle: BRAND.textSubtle,
  primary: BRAND.red,
  primarySoft: BRAND.redSoft,
  primaryPressed: BRAND.redPressed,
  line: BRAND.borderSoft,
  white: '#FFFFFF',
  black: BRAND.ink,
  peach50: BRAND.sandSoft,
  peach100: '#FCE8C4',
  peach200: BRAND.sand,
  peach300: '#F5C36D',
  peach400: '#E7A85E',
  peach500: '#D58853',
  peach600: BRAND.red,
  brown: BRAND.inkSoft,
  brownDark: BRAND.ink,
  sceneBg: BRAND.darkPage,
  sceneSurface: BRAND.darkSurface,
  sceneBorder: BRAND.darkBorder,
  sceneText: BRAND.darkText,
  sceneMuted: BRAND.darkMuted,
  card: BRAND.creamSoft,
  cardDark: BRAND.darkSurface,
  borderDark: BRAND.darkBorder,
  textDark: BRAND.darkText,
  textMutedDark: BRAND.darkMuted,
  textSubtleDark: BRAND.darkSubtle,
  orange: BRAND.red,
  orangeSoft: BRAND.redSoft,
  blue: BRAND.inkSoft,
  blueSoft: '#F6ECE4',
  green: BRAND.success,
  pill: '#FFF8F0',
  pillDark: BRAND.darkSurfaceAlt,
} as const;

export const Colors = {
  light: {
    text: BrandPalette.text,
    background: BrandPalette.page,
    backgroundElement: BrandPalette.surface,
    backgroundSelected: BrandPalette.surfaceAlt,
    textSecondary: BrandPalette.textMuted,
    border: BrandPalette.border,
    primary: BrandPalette.primary,
  },
  dark: {
    text: BrandPalette.sceneText,
    background: BrandPalette.sceneBg,
    backgroundElement: BrandPalette.sceneSurface,
    backgroundSelected: BrandPalette.darkSurfaceAlt,
    textSecondary: BrandPalette.sceneMuted,
    border: BrandPalette.sceneBorder,
    primary: BrandPalette.peach200,
  },
} as const;

export type ThemeColor = keyof typeof Colors.light & keyof typeof Colors.dark;

export const Fonts = Platform.select({
  ios: {
    sans: 'system-ui',
    serif: 'ui-serif',
    rounded: 'ui-rounded',
    mono: 'ui-monospace',
  },
  default: {
    sans: 'normal',
    serif: 'serif',
    rounded: 'normal',
    mono: 'monospace',
  },
  web: {
    sans: 'var(--font-display)',
    serif: 'var(--font-serif)',
    rounded: 'var(--font-rounded)',
    mono: 'var(--font-mono)',
  },
});

export const Spacing = {
  half: 2,
  one: 4,
  two: 8,
  three: 16,
  four: 24,
  five: 32,
  six: 64,
} as const;

export const Radius = {
  sm: 12,
  md: 16,
  lg: 20,
  xl: 24,
  pill: 999,
} as const;

export function createShadow(opacity = 0.12, radius = 18, height = 10) {
  return Platform.select({
    ios: {
      shadowColor: BRAND.ink,
      shadowOpacity: opacity,
      shadowRadius: radius,
      shadowOffset: { width: 0, height },
    },
    android: {
      elevation: Math.max(4, Math.round(radius * 0.75)),
    },
    default: {},
  });
}

export const ConsumerServiceThemes = {
  food: {
    page: BrandPalette.page,
    hero: '#211714',
    heroSoft: '#513028',
    heroAccent: BrandPalette.peach200,
    heroText: BrandPalette.sceneText,
    heroSub: '#E4D1BE',
    searchPlaceholder: 'Search biryani, cake, dosa...',
    bannerEyebrow: 'Freshly picked for today',
    bannerTitle: 'Premium comfort, faster discovery',
    bannerCopy: 'Cleaner hierarchy, warmer tones and stronger merchant storytelling for the main consumer app.',
    statusBar: 'light-content' as const,
  },
  warehouse: {
    page: '#FCF7EF',
    hero: '#F6E6CB',
    heroSoft: '#FFF3E0',
    heroAccent: BrandPalette.peach300,
    heroText: BrandPalette.text,
    heroSub: BrandPalette.textMuted,
    searchPlaceholder: 'Search fruits, dry fruits, dairy...',
    bannerEyebrow: 'Essentials in minutes',
    bannerTitle: 'Quick baskets, calmer browsing',
    bannerCopy: 'Everyday grocery tasks feel more premium with cleaner chips, cards and deal placement.',
    statusBar: 'dark-content' as const,
  },
  eatout: {
    page: '#FBF3EC',
    hero: '#F3E1D3',
    heroSoft: '#FFF4EA',
    heroAccent: '#EFB574',
    heroText: BrandPalette.text,
    heroSub: BrandPalette.textMuted,
    searchPlaceholder: 'Search restaurant, area or vibe...',
    bannerEyebrow: 'Plans made easier',
    bannerTitle: 'Reserve nights with less clutter',
    bannerCopy: 'Offer-led presentation and richer spacing make dineout feel demo-ready.',
    statusBar: 'dark-content' as const,
  },
  scenes: {
    page: BrandPalette.sceneBg,
    hero: '#211914',
    heroSoft: '#342820',
    heroAccent: '#8B5138',
    heroText: BrandPalette.sceneText,
    heroSub: BrandPalette.sceneMuted,
    searchPlaceholder: 'Search events, creators, experiences...',
    bannerEyebrow: 'Weekend energy',
    bannerTitle: 'Plans worth stepping out for',
    bannerCopy: 'The dark experience stays editorial while still belonging to Grab Basket.',
    statusBar: 'light-content' as const,
  },
} as const;

export const StoreServiceThemes = {
  food: {
    page: BrandPalette.page,
    hero: '#201613',
    heroAlt: '#4A2A24',
    heroAccent: BrandPalette.peach200,
    primary: BrandPalette.primary,
    primarySoft: BrandPalette.primarySoft,
    searchBg: BrandPalette.surface,
    textOnHero: BrandPalette.sceneText,
    pillBg: 'rgba(255,255,255,0.12)',
    pillText: BrandPalette.sceneText,
    cartBg: BrandPalette.ink,
  },
  warehouse: {
    page: '#FCF7EF',
    hero: '#EFD8BA',
    heroAlt: '#F8E8D1',
    heroAccent: BrandPalette.primary,
    primary: BrandPalette.primary,
    primarySoft: BrandPalette.primarySoft,
    searchBg: BrandPalette.surface,
    textOnHero: BrandPalette.text,
    pillBg: 'rgba(20,18,16,0.07)',
    pillText: BrandPalette.text,
    cartBg: BrandPalette.ink,
  },
  eatout: {
    page: '#FBF3EC',
    hero: '#EEDAC7',
    heroAlt: '#F7E8DB',
    heroAccent: BrandPalette.primary,
    primary: BrandPalette.primary,
    primarySoft: BrandPalette.primarySoft,
    searchBg: BrandPalette.surface,
    textOnHero: BrandPalette.text,
    pillBg: 'rgba(20,18,16,0.07)',
    pillText: BrandPalette.text,
    cartBg: BrandPalette.ink,
  },
  scenes: {
    page: BrandPalette.sceneBg,
    hero: '#120F0D',
    heroAlt: '#2B211D',
    heroAccent: '#855B46',
    primary: BrandPalette.peach200,
    primarySoft: 'rgba(255,255,255,0.12)',
    searchBg: BrandPalette.sceneSurface,
    textOnHero: BrandPalette.sceneText,
    pillBg: 'rgba(255,255,255,0.1)',
    pillText: BrandPalette.sceneText,
    cartBg: BrandPalette.peach200,
  },
} as const;

export const ConsumerTabThemes = {
  food: {
    activeTint: BrandPalette.primary,
    inactiveTint: BrandPalette.subtle,
    barBackground: 'rgba(255,253,249,0.98)',
    barBorder: BrandPalette.border,
    shadowColor: BRAND.ink,
    focusedSurface: BrandPalette.primarySoft,
    focusedBorder: '#F7C8CF',
    iconSurface: '#FFF3F4',
    badgeBackground: BrandPalette.primary,
    badgeText: BrandPalette.white,
    sceneBackground: BrandPalette.page,
    titleMap: {
      index: 'Home',
      explore: 'Explore',
      reorder: 'Reorder',
      account: 'Profile',
    },
    iconMap: {
      index: 'home-outline',
      explore: 'compass-outline',
      reorder: 'reload-outline',
      account: 'person-outline',
    },
  },
  warehouse: {
    activeTint: BrandPalette.primary,
    inactiveTint: BrandPalette.subtle,
    barBackground: 'rgba(255,253,249,0.98)',
    barBorder: BrandPalette.border,
    shadowColor: BRAND.ink,
    focusedSurface: '#FFF2E8',
    focusedBorder: '#F5D2C6',
    iconSurface: '#FFF1EA',
    badgeBackground: BrandPalette.primary,
    badgeText: BrandPalette.white,
    sceneBackground: '#FCF7EF',
    titleMap: {
      index: 'Mart',
      explore: 'Aisles',
      reorder: 'Reorder',
      account: 'Profile',
    },
    iconMap: {
      index: 'basket-outline',
      explore: 'grid-outline',
      reorder: 'reload-outline',
      account: 'person-outline',
    },
  },
  eatout: {
    activeTint: BrandPalette.primary,
    inactiveTint: BrandPalette.subtle,
    barBackground: 'rgba(255,253,249,0.98)',
    barBorder: BrandPalette.border,
    shadowColor: BRAND.ink,
    focusedSurface: '#FFF1E9',
    focusedBorder: '#F2D5C8',
    iconSurface: '#FFF1E8',
    badgeBackground: BrandPalette.primary,
    badgeText: BrandPalette.white,
    sceneBackground: '#FBF3EC',
    titleMap: {
      index: 'Dineout',
      explore: 'Explore',
      reorder: 'New & Hot',
      account: 'Profile',
    },
    iconMap: {
      index: 'restaurant-outline',
      explore: 'sparkles-outline',
      reorder: 'flame-outline',
      account: 'person-outline',
    },
  },
  scenes: {
    activeTint: BrandPalette.peach200,
    inactiveTint: '#B79D88',
    barBackground: 'rgba(23,19,16,0.98)',
    barBorder: BrandPalette.sceneBorder,
    shadowColor: BRAND.ink,
    focusedSurface: BrandPalette.darkSurfaceAlt,
    focusedBorder: '#665146',
    iconSurface: '#372A23',
    badgeBackground: BrandPalette.peach200,
    badgeText: BrandPalette.text,
    sceneBackground: BrandPalette.sceneBg,
    titleMap: {
      index: 'Scenes',
      explore: 'Explore',
      reorder: 'Saved',
      account: 'Profile',
    },
    iconMap: {
      index: 'sparkles-outline',
      explore: 'compass-outline',
      reorder: 'bookmark-outline',
      account: 'person-outline',
    },
  },
} as const;

export const AppShellThemes = {
  delivery: {
    page: '#F9F3EC',
    barBackground: 'rgba(255,253,249,0.98)',
    barBorder: BrandPalette.border,
    activeTint: BrandPalette.primary,
    inactiveTint: BrandPalette.subtle,
    focusedSurface: BrandPalette.primarySoft,
    focusedBorder: '#F6CCD2',
    iconSurface: '#FFF1F3',
    shadowColor: BRAND.ink,
  },
  partner: {
    page: '#FBF6EE',
    barBackground: 'rgba(255,253,249,0.98)',
    barBorder: BrandPalette.border,
    activeTint: BrandPalette.primary,
    inactiveTint: BrandPalette.subtle,
    focusedSurface: '#FFF0E7',
    focusedBorder: '#F2D2C4',
    iconSurface: '#FFF1E8',
    shadowColor: BRAND.ink,
  },
} as const;

export const BottomTabInset = Platform.select({ ios: 50, android: 80 }) ?? 0;
export const MaxContentWidth = 800;
